############################
## CHANGE THESE
############################

baseURL: 'https://SizhuangHe.github.io/my-site'
title: Sizhuang's website

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


